#Workflow name
name: Dockerization
on:
  workflow_dispatch:
  push:
    branches: [ main, workflows ]
jobs:
  docker:
    name: Dockerization
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.7.0

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cocletima-front:latest

      container: node:10.19-jessie
